# Generated by Django 5.1.2 on 2024-10-22 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkoyUQaux4PEUmEPGc7PodeN8XbgC4aOBsug&s', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('cities', models.TextField(default='[]', help_text='Please fill this field, or your profile will not be shown to users.')),
                ('mapLink', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('picture', models.CharField(blank=True, max_length=10000, null=True)),
                ('qualification', models.CharField(blank=True, default='MBBS', max_length=100, null=True)),
                ('qualification_doc', models.CharField(blank=True, max_length=10000, null=True)),
                ('identity_doc', models.CharField(blank=True, max_length=10000, null=True)),
                ('degree_filename', models.CharField(blank=True, max_length=10000, null=True)),
                ('experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bio', models.CharField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('rating_no', models.IntegerField(default=0)),
                ('time_slot', models.TextField(blank=True, default='[]', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_category', to='doctors.doctorcategory')),
            ],
        ),
        migrations.AddField(
            model_name='doctorcategory',
            name='doctors',
            field=models.ManyToManyField(related_name='categories', to='doctors.doctors'),
        ),
    ]
