# Generated by Django 5.1.2 on 2024-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='cities',
        ),
        migrations.AddField(
            model_name='doctors',
            name='city',
            field=models.CharField(blank=True, help_text="FILL IT ELSE YOU WON'T BE SEARCHED", max_length=100),
        ),
    ]
